[build]
  functions = "netlify/functions"

[context.production]
command = "npm install @rollup/rollup-linux-x64-gnu @esbuild/linux-x64@0.21.5 --no-save && npm run build"
publish = "dist"
branch = "main"

[context.deploy-preview]
command = "npm run build"
publish = "dist"

[context.staging]
command = "npm run build"
publish = "dist"
branch = "develop"
